config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'videos/search'
  end
  
  devise_for :users
  root to: 'pages#home'

  resources :videos do
    member do
      post 'toggle_favorite', to: "videos#toggle_favorite"
    end
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]

  resources :lists

  namespace :api, defaults: {format: :json} do
    get 'videos/:id/search', to: 'videos#search'
  end

  get 'videos/:id/text_search', to: 'videos#text_search', as: :text_search
  get 'favorites', to: 'videos#show_favorite'
end

app/models/video.rb
class Video < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :lists, through: :bookmarks
  acts_as_favoritable

  pg_search_scope :search_by_title_or_transcript,
    against: [ :title, :description, :captions ],
    using: {
      tsearch: { prefix: true,
      }
    }

  def extract_url_from_body
    URI.extract(body).first
  end
end

app/controllers/api/videos_controller.rb
class Api::VideosController < ApplicationController
  def search
    set_video
    array_of_text = []
    @video.captions.each do |hash|
      if hash["text"].include? params[:query]
        array_of_text << hash
      end
    end
    render json: array_of_text
  end

    private
  def set_video
    @video = Video.find(params[:id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include ActionView::Helpers::UrlHelper
  require "open-uri"
  before_action :set_video, only: %i[show edit update destroy toggle_favorite]

  def index
    @favorite_videos = current_user.favorited_by_type('Video')
    if params[:query].present?
      @videos = policy_scope(Video).search_by_title_or_transcript(params[:query])
      @search_query = params["query"]
      @caption_results = []
      @videos.each_with_index.map do |video, index|
        video_captions = []
        video.captions.each_with_index.map do |caption, index|
          next unless caption["text"].include? @search_query

          # create for last index or first index
          case index
          when 0
            video_captions.push([video.captions[index]["start_seconds"],
                                 (video.captions[index]["start"] + " " + caption["text"] + " " + video.captions[index + 1]["text"] + "...")])
          when video.captions.length - 1
            video_captions.push([video.captions[index - 1]["start_seconds"],
                                 (video.captions[index - 1]["start"] + " ..." + video.captions[index - 1]["text"] + " " + caption["text"] + " " + video.captions[index + 1]["text"] + "...")])
          else
            video_captions.push([video.captions[index - 1]["start_seconds"],
                                 (video.captions[index - 1]["start"] + " ..." + video.captions[index - 1]["text"] + " " + caption["text"] + " " + video.captions[index + 1]["text"] + "...")])
          end
        end
        @caption_results.push(video_captions)
      end

    else
      @videos = policy_scope(Video)
    end
    redirect_to videos_path unless current_page?(videos_path)
  end

  def show
    @bookmark = Bookmark.new
    @video = Video.find(params[:id])
    yt = YoutubeApi.new
    unless @video.description?
      p "get captions"
      if  @video.captions != {}
      @video_captions = @video.captions[0..5]
      @new_description = ""
      @video_captions.each do |caption|
        @new_description.concat(caption["text"] + " ")
      end
      @new_description.concat("...")
      @video.description = @new_description
      @video.save
    end
    end
    
    unless @video.photo.attached?
      yt = YoutubeApi.new
      begin
        @thumbnail = yt.get_thumbnail(@video)
        file = URI.open(@thumbnail)
      rescue OpenURI::HTTPError
        p "no thumbnail"
      else
        p "attach the thumbnail found"
        @video.photo.attach(io: file, filename: 'thumbnail.png', content_type: 'image/png')
      end
    end

    unless @video.duration?
      yt = YoutubeApi.new
      @video.duration = yt.get_duration(@video)
      @video.save
    end

    authorize @video
    if @video.captions == {}
      yt = YoutubeApi.new
      @video.captions = yt.get_captions(@video)
      @video.save
    end
    yt = YoutubeApi.new
    if params["language"]
      language = params["language"]
      @translation = yt.translate(@video, language)
    else
      @translation = nil
    end
  end

  def create
    # Make an API call to the YouTube API.
    yt = YoutubeApi.new
    video = yt.upload_video(
      params[:video][:video_file].to_path,
      params[:video][:title],
      params[:video][:description]
    )
    @video = Video.new(video_params)
    @video.user = current_user
    @video.video_source = video.id
    @video.captions = {}
    if @video.save!
      flash[:success] = 'Video added!'
      redirect_to videos_path
    else
      render :new
    end
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def update
    @video.update(video_params)
    redirect_to videos_path(@video)
  end

  def destroy
    @video.destroy
    redirect_to videos_path
  end

  def text_search
    set_video
    array_of_text = []
    @video.captions.each do |hash|
      array_of_text << hash if hash["text"].include? params[:text_query]
    end
    render json: array_of_text
  end

  def toggle_favorite
    current_user.favorited?(@video) ? current_user.unfavorite(@video) : current_user.favorite(@video)
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def show_favorites
    @favorites = current_user.all_favorited
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :description)
  end
end

app/views/videos/_form-edit.html.erb
  <%= simple_form_for @video, remote: true do |f| %>
    <%= f.input :title, label: 'Title', error: 'title is mandatory, please specify one' %>
    <%= f.input :description, as: :text, :input_html => { :rows => 6 }, label: 'Description', error: 'description is mandatory, please specify one' %>
    <%= f.submit "Edit", class: "btn btn-primary form-button" %>
  <% end %>

app/views/videos/_form-new.html.erb
  <%= simple_form_for @video, remote: true do |f| %>
    <%= f.input :title, label: 'Title', error: 'title is mandatory, please specify one' %>
    <%= f.input :description, as: :text, :input_html => { :rows => 6 }, label: 'Description', error: 'description is mandatory, please specify one' %>
    <%= f.input :video_file, as: :file, label: 'Select video file', error: 'must have file' %>
    <%= f.button :submit, class: "btn btn-primary form-button", value: 'Upload' %>
  <% end %>

app/views/videos/_video-caption-card.html.erb
<div class="caption-text m-4">
  <h3 class="video-description">Transcription</h3>
  <!-- Edit-Modal -->
  <div class="modal fade" id="form-edit" tabindex="-1" role="dialog" aria-labelledby="form-edit" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 800px!important;" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-6">
              <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
              <lottie-player src="https://assets7.lottiefiles.com/packages/lf20_kwljzgsc.json"  background="transparent" loop autoplay></lottie-player>
            </div>
            <div class="col-md-6">
              <%= render "form-edit", video: @video %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Delete-Modal -->
  <div class="modal fade" id="form-delete" tabindex="-1" role="dialog" aria-labelledby="form-delete" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 500px!important;" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-6">
              <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
              <lottie-player src="https://assets9.lottiefiles.com/packages/lf20_dsqblnrv.json"  background="transparent" loop autoplay></lottie-player>
            </div>
            <div class="col-md-6">
              <p>Are you sure?</p>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_to "Delete", video_path(@video), :method => :get, class: "btn btn-primary",
                method: :delete %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex">
  <%# search %>
  <div class="form-inline flex-grow-1">
    <%= form_tag text_search_path, method: :get, class: 'form-text', remote: true do %>
      <%= text_field_tag :text_query,
              params[:text_query],
              class: "form-control form-color form-radius ",
              placeholder: "Search",
              data: {
              search_target: "input"
              }
              %>
      <%= submit_tag "Search", class: "btn btn-primary btn-border btn-radius btn-font-color", id: "btn-caption-search", data: { search_target: 'button' } %>
    <% end %>
  </div>
  <%# add to list %>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownList" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
      Add To List
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <% current_user.lists.each do |list| %>
        <a class="dropdown-item list-name select-list" href="" data-my-id="<%= list.id %>">
          <%= list.name %></a>
      <% end %>
      <a class="dropdown-item" href="/lists/new">+ Create New List</a>
    </div>
  </div>
  <%# translate %>
  <div classs="dropdown">
    <button class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
      Translate
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="/videos/<%= @video.id %>">English</a>
      <a class="dropdown-item" href="/videos/<%= @video.id %>?language=zh">Chinese</a>
      <a class="dropdown-item" href="/videos/<%= @video.id %>?language=ja">Japanese</a>
      <a class="dropdown-item" href="/videos/<%= @video.id %>?language=ar">Arabic</a>
      <a class="dropdown-item" href="/videos/<%= @video.id %>?language=id">Indonesian</a>
      <a class="dropdown-item" href="/videos/<%= @video.id %>?language=tl">Tagalog</a>
      <a class="dropdown-item" href="/videos/<%= @video.id %>?language=nl">Dutch</a>
      <a class="dropdown-item" href="/videos/<%= @video.id %>?language=de">German</a>
    </div>
  </div>
  </div>
</div>
<div class="card card-body m-4" id="caption_container">
  <% if @video.captions.length === 0 %>
    "Sorry! Transcript not available yet"
  <% else %>
    <div id="fullTranscript">
      <% @video.captions.each_with_index do |caption, index| %>
        <% caption["text"] = @translation[index] if @translation %>
        <% if index % 10 == 0 %>
          <br>
          <br>
        <% end %>
        <span><%= content_tag("a"," #{caption["text"]}", data: { start_seconds: caption["start_seconds"], end_seconds: caption["end_seconds"]}, class: "timecode") %></span>
      <% end %>
    </div>
    <div id="searchResults">
    </div>
  <% end %>
</div>
<%# hidden simple form for adding video to list %>
<%= simple_form_for [@video, @bookmark], html: { class: "hide-form"} do |f| %>
  <%= f.association :list %>
  <%= f.submit 'Add to List', class: "button-list" %>
<% end %>
<%= javascript_pack_tag 'add-to-list' %>

app/views/videos/_video-cards.html.erb
<h2>Your videos (<%= @videos.count%>)</h2>
  <div class="grid">
    <% @videos.each do |video| %>
      <%= link_to video_path(video) do %>
        <div class="grid-item card">
          <%# cl_image_tag video.photo.key, :height=>200, :crop=>"fill", :class => "img-card" %>
          <div class="card-body">
            <p> <%= video.description %></p>
            <h5> <%= video.title %></h5>
            <p> <%= video.created_at %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/videos/_video-index-cards.html.erb
<!-- VIDEOHEADER-->
<% if  @search_query === nil %>
  <div class="pageHeaderTitle">My Videos (<%= @videos.count%>)</div>
<% else %>
  <div class="pageHeaderTitle"> Results for "<%= @search_query %>" (<%= @videos.count%>) </div>
  <% end %>
  <% @videos.each_with_index do |video, index| %>
    <%= link_to video_path(video) do %>
    <!-- VIDEO-CARD-->
      <article>
        <div class="videocard">

        <!-- VIDEO-THUMBNAIL-->
          <div class="videocard-thumbnail">
            <% if video.photo.attached? %>
              <%= cl_image_tag video.photo.key, :aspect_ratio=>"16:9", :width=>500, :crop=>"fill", class: 'rounded' %>
            <% else %>
              <%= image_tag "video-default.png", :aspect_ratio=>"16:9", :width=>500, :crop=>"fill", class: 'rounded'  %>
            <% end %>
          </div>
          <!-- VIDEO INFO -->
          <div class="videocard-info flex-grow-1">
            <h2 class="videocard-title"><%= video.title %></h2>
            <%= link_to toggle_favorite_video_path(video), remote: true, method: :post do %>
            
            <!-- VIDEO FAVORITE -->  
            <div class="like-icon mx-2" data-id="<%= video.id %>">
              <% if current_user.favorited?(video) %>
                <i class="fas fa-heart"></i>
              <% else %>
                <i class="far fa-heart"></i>
              <% end %>
            </div>
          <% end %>
            <!-- SUB-INFO -->
            <div class="videocard-info">
                <% if video.captions? %>
                  <span class="badge badge-success" id="status-completed">Processed</span>
                <% else %>
                  <span class="badge badge-warning" id="status-pending">Pending</span>
                <% end %>
                 <span><i class="fas fa-calendar-alt mr-2"></i><%= video.created_at.to_date %> <span>
            </div>
            <%# <div class="videocard-bar"></div> %>

            
            <div class="videocard-description"><%= video.description %></div>
      <% end %>
            <ul class="videocard-tagbox">
              <% if video.lists.exists? %>
                <% video.lists.each do |tag| %>
                  <li class="tag-item"><i class="fas fa-tag mr-2"></i><%= link_to tag.name, list_path(tag) %></li>
                <% end %>
              <% end %>
                <% if video.duration? %>
                  <li class="tag-item"><i class="fas fa-clock mr-2"></i><%= video.duration %> minutes</li>
                <% end %>
             <% if local_assigns[:list] %>
              <%= button_to "Delete", bookmark_path(list.bookmarks.find_by(video: video)), :method => :get, class: "btn btn-primary",
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
            <% end %>
            </ul>
      </div>
  </div>

  <% if @caption_results != nil %>
        <div class="temp_styling">
          <% if @caption_results[index] != [] %>
            <h3>Results from Transcript </h3>
            <ul>
              <% @caption_results[index].each_with_index do |caption, index| %>
                <%= link_to video_path(video, :start_skim => caption[0]) do %>
                  <li class="timecode">
                    <%= caption[1].gsub!(/#{@search_query}\w*\b/, '<span class = "search_term_highlight">\0</span>').html_safe %>
                  </li>
                <% end %>
               <% end %>
            </ul>
         <% end %>
      </div>
    <% end %>
   <% end %>
  </article>

app/views/videos/_video-player.html.erb
<div class="embed-responsive embed-responsive-16by9">
  <%= content_tag("div","", data: { video_source: @video.video_source}, id: "player") %>
</div>
<div class="video-description-card m-4">
  <div class="video-description-card-title d-flex align-items-center">
    <h1 ><%= @video.title %></h1>
    <div class="dropdown ml-4">
      <a id="dropdownList" data-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-h" style="font-size:15px; color:#2b2a2a;"></i>
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="#" data-toggle="modal">
          <a class="dropdown-item" data-toggle="modal" data-target="#form-edit">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Edit
          </a>
          <a class="dropdown-item" data-toggle="modal" data-target="#form-delete">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Delete
          </a>
        </div>
      </div>
    </div>
    <ul class="videoplayer-tagbox d-flex">
      <% if @video.lists.exists? %>
        <% @video.lists.each do |tag| %>
          <li class="tag-item"><i class="fas fa-tag mr-2"></i><%= link_to tag.name, list_path(tag) %></li>
        <% end %>
      <% end %>
      <% if @video.duration? %>
        <li class="tag-item"><i class="fas fa-clock mr-2"></i><%= @video.duration %> minutes</li>
      <% end %>
    </ul>
    <hr>
    <p><%= @video.description %></p>
  </div>

app/views/videos/edit.html.erb
  <%= render "form-edit", video: @video %>

app/views/videos/index.html.erb
<%= render 'videos/video-index-cards' %>

app/views/videos/new.html.erb
<br>
<div class="form-container">
  <h2 class="form-title">  🎥 &nbsp;Upload Video</h2>
  <%= render "form-new", video: @video %></div>
<br>

app/views/videos/show.html.erb
    
  <div class="row no-gutters video-content">
    <div class="col-lg-6">
      <%= render 'videos/video-player' %>
    </div>
    <div class="col-lg-5">
      <%= render 'videos/video-caption-card' %>
    </div>
  </div>

<style>
  .current_caption{
    background-color:yellow;
    color:black;
  }
  #caption_container {
      list-style-type: none;
      overflow: auto;
          min-height:40vh;
    max-height:70vh;}
  p{
      color:black;
  }
</style>

app/views/videos/show_favorite.html.erb
<% if current_user.present? && current_user.all_favorited.present? %>
  <% @videos = current_user.all_favorited %>
    <%= render 'videos/video-index-cards'%>
  <% else %>
	  <div class="h1 text-center text-dark" id="pageHeaderTitle">It's empty here... add some favorites!</div>
<% end %>