config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'videos/search'
  end
  
  devise_for :users
  root to: 'pages#home'

  resources :videos do
    member do
      post 'toggle_favorite', to: "videos#toggle_favorite"
    end
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]

  resources :lists

  namespace :api, defaults: {format: :json} do
    get 'videos/:id/search', to: 'videos#search'
  end

  get 'videos/:id/text_search', to: 'videos#text_search', as: :text_search
  get 'favorites', to: 'videos#show_favorite'
end

app/views/shared/navbar/_navbar-main.html.erb
<!-- SIDEBAR-->
<%= render 'shared/navbar/navbar-side' %>

app/views/shared/navbar/_navbar-side.html.erb
<!-- SIDE-->
<div class="wrapper">
    <nav id="sidebar">
        <!-- LOGO-->
        <div class="sidebar-header">
            <%= link_to root_path, class: "navbar-brand" do %>
                <%= cl_image_tag("https://res.cloudinary.com/elyse/image/upload/v1630588994/pscriber-logo-lime_ouqxjs.png", class: 'logo' ) %> 
            <% end %>
        </div>
         
        <div class="sidebar-search">
        
        <form accept-charset="UTF-8" action="/videos" method="get"
                              class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-600 navbar-search">
            <input type="query" name="query" type="text" class="form-control form-control-lg" placeholder="Search a keyword"><button type="submit" class="search-button">
    <i class="fas fa-search"></i>
  </button> 
  </form>
        </div>

        <!-- MENU -->
        <ul class="navbar-nav accordion" id="accordionSidebar">
            
            <li class="nav-item active">
            <%= link_to videos_path, class: "nav-link" do %>
                <%= image_tag "video.svg", class: "nav-icon" %><span class="nav-item"> My Videos</span>
            <% end %>
            </li>
            <li class="nav-item active">
            <%= link_to new_video_path, class: "nav-link" do %>
                <%= image_tag "upload.svg", class: "nav-icon" %><span class="nav-item">  Upload a Video</span>
            <% end %>
            </li>

            <li class="nav-item active">
             <%= link_to favorites_path, class: "nav-link" do %>
                <%= image_tag "heart.svg", class: "nav-icon" %><span class="nav-item">  Favorites</span>
            <% end %>
            </li>

            <li class="nav-item active">
            <%= link_to "", class: "nav-link" do %>
                <%= image_tag "bookmark.svg", class: "nav-icon" %><span class="nav-item">  Bookmarks</span>
                </a>
            <% end %>
            <% if current_user.present? %>
                <ul>
                    <% current_user.lists.each do |list| %>
                    <li><a class= "bookmark-link" href="/lists/<%=list.id%>" data-my-id="<%= list.id %>">
                        # <%= list.name %></a></li>
                    <% end %>
                    <a class="bookmark-link" href="/lists/new"> + Create new</a>
                <% end %>
                </ul>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-1 rounded" id="bookmark-drop">
                </div>
            </div>
            </li>
        </ul>
    </nav>
</div>

<%# <% <div class="row">
        <div class="col-md-2">
        <!-- TOGGLE-->
                
                    <button class="menu" id="sidebarCollapse" onclick="this.classList.toggle('opened');this.setAttribute('aria-expanded', this.classList.contains('opened'))" aria-label="Main Menu">
                            <svg width="50" height="50" viewBox="0 0 100 100">
                            <path class="line line1" d="M 20,29.000046 H 80.000231 C 80.000231,29.000046 94.498839,28.817352 94.532987,66.711331 94.543142,77.980673 90.966081,81.670246 85.259173,81.668997 79.552261,81.667751 75.000211,74.999942 75.000211,74.999942 L 25.000021,25.000058" />
                            <path class="line line2" d="M 20,50 H 80" />
                            <path class="line line3" d="M 20,70.999954 H 80.000231 C 80.000231,70.999954 94.498839,71.182648 94.532987,33.288669 94.543142,22.019327 90.966081,18.329754 85.259173,18.331003 79.552261,18.332249 75.000211,25.000058 75.000211,25.000058 L 25.000021,74.999942" />
                        </svg>
                    </button>
    </div>
  </div> %>
<!-- jQuery CDN - Slim version (=without AJAX) -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script type="text/javascript">
  $(document).ready(function () {
      $('#sidebarCollapse').on('click', function () {
  
          $('#sidebar').toggleClass('active');
      });
  });
</script>

app/views/shared/navbar/_navbar-top.html.erb
<!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                console.log("hello");

// #get element by id by the sidebar
// add/toggle class active

                $('#accordionSidebar"').toggleClass('active');
            });
        });
    </script>






    <div class="flex-items"><%= render 'shared/navbar/search' %></div> 
  <div class="flex-items"><%= render 'shared/navbar/user' %></div>

app/views/shared/navbar/_user.html.erb
<li class="nav-item dropdown no-arrow">
  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
        data-toggle="dropdown"  aria-expanded="false">
    <%= image_tag "user", class: "nav-user" %>
  </a>
  <!-- Dropdown - User Information -->
  <div class="dropdown-menu"
                    aria-labelledby="userDropdown">
    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
      <% if user_signed_in? %>
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a>
        <a class="dropdown-item" href="#">
          <div class="dropdown-divider"></div>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </a>
      <% end %>
    </div>
  </li>